### ISSUE TITLE
Incompatibility with Fabric-Discord Link

### ISSUE THREAD

**Issue by thecatcore** [LoganDark/fabric-console#3]
Hi, I'm the author of the Fabric Discord Link mod and I've been tracking an issue that lead me to your mod ([#142](https://github.com/arthurbambou/Fabric---Discord-Link/issues/142)). I had found a hacky solution to fix the issue however I would have preferred to find another way. This is the main reason I opened #2 .

**Comment by LoganDark** [comment]
I'm so sorry I never got to your pull request. For some reason GitHub didn't notify me. I'll give it a quick look.

**Comment by LoganDark** [comment]
This issue will be closed once the fix is published to CurseForge, which should be in about a half hour

**Comment by thecatcore** [comment]
:+1:

**Comment by LoganDark** [comment]
Published: https://www.curseforge.com/minecraft/mc-mods/fabric-console/files/3336835

TY!
