### ISSUE TITLE
Does not support 1.17

### ISSUE THREAD

**Issue by solonovamax** [LoganDark/fabric-console#5]
This is a duplicate of #4, but that was closed and locked.
You should probably just leave the issue open until you get time.

I also might PR the change if I get time.

**Comment by LoganDark** [comment]
> but that was closed and locked.

Because it was begging. There are more civilized ways to request features or point out lack of support.

FWIW, if they haven't changed text components for the 5th time this year, it shouldn't be too hard to support 1.17.

**Comment by LoganDark** [comment]
#6 has prompted me to get a Fabric toolchain setup on my new computer, so I'll look into this more in a bit.

**Comment by LoganDark** [comment]
The mod supports 1.17 now: [GitHub](https://github.com/LoganDark/fabric-console/releases/tag/1.0.5%2B1.17.1) (fast) or [CurseForge](https://www.curseforge.com/minecraft/mc-mods/fabric-console/files/3512399) (slow).
